# Generated by Django 2.0.7 on 2018-08-15 04:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtendimentoTecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Atendimento')),
            ],
            options={
                'verbose_name': 'Técnica X Atendimento',
                'verbose_name_plural': 'Técnicas X Atendimentos',
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaFerida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Característica da ferida',
                'verbose_name_plural': 'Características das feridas',
            },
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Doença',
                'verbose_name_plural': 'Doenças',
            },
        ),
        migrations.CreateModel(
            name='Ferida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Ferida',
                'verbose_name_plural': 'Feridas',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(default='IMG15082018014154', max_length=80)),
                ('foto', models.ImageField(upload_to='imagens/')),
                ('segmented_image', models.ImageField(blank=True, null=True, upload_to='imagens_segmentadas/')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Atendimento')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=250)),
                ('sexo', models.CharField(max_length=1)),
                ('dataNascimento', models.DateTimeField()),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Técnica',
                'verbose_name_plural': 'Técnicas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='auth.User')),
                ('nomeUsuario', models.CharField(blank=True, max_length=250, null=True)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.AddField(
            model_name='profissional',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Usuario'),
        ),
        migrations.AddField(
            model_name='ferida',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Paciente'),
        ),
        migrations.AddField(
            model_name='doenca',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Paciente'),
        ),
        migrations.AddField(
            model_name='atendimentotecnica',
            name='tecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Tecnica'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='caracteristica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samuv_site.CaracteristicaFerida'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='ferida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Ferida'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Profissional'),
        ),
    ]
