# Generated by Django 2.0.7 on 2018-09-13 18:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG13092018030216', max_length=80),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=3),
        ),
    ]
