# Generated by Django 2.0.7 on 2018-09-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0002_auto_20180918_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='imagemAnalisada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG18092018024951', max_length=80),
        ),
    ]
