# Generated by Django 2.0.7 on 2018-09-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0002_auto_20180820_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='imagemAnalisada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG07092018075245', max_length=80),
        ),
    ]
