# Generated by Django 2.0.7 on 2018-09-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0003_auto_20180907_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG09092018050349', max_length=80),
        ),
    ]
