# Generated by Django 2.0.7 on 2018-09-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0006_auto_20180916_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='marked_image',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG16092018080925', max_length=80),
        ),
    ]
