# Generated by Django 2.0.7 on 2018-09-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0003_auto_20180918_1449'),
        ('samuv_site', '0007_auto_20180916_2009'),
    ]

    operations = [
    ]
