# Generated by Django 2.0.7 on 2018-09-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0008_merge_20180918_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG22092018115141', max_length=80),
        ),
    ]
