# Generated by Django 2.0.7 on 2018-09-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0009_auto_20180922_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG22092018115420', max_length=80),
        ),
    ]
