# Generated by Django 2.0.7 on 2018-09-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0010_auto_20180922_1154'),
        ('samuv_site', '0002_auto_20180913_1502'),
    ]

    operations = [
    ]
