# Generated by Django 2.0.7 on 2018-09-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0012_auto_20180928_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG29092018023629', max_length=80),
        ),
    ]
