# Generated by Django 2.0.7 on 2018-09-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0013_auto_20180929_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG30092018064432', max_length=80),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dataNascimento',
            field=models.DateField(),
        ),
    ]
