# Generated by Django 2.0.7 on 2018-10-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0014_auto_20180930_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG29102018030922', max_length=80),
        ),
    ]
