# Generated by Django 2.0.7 on 2018-10-31 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0018_auto_20181031_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitosPessoais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroRefeicoesDia', models.IntegerField(default=0)),
                ('habitosAlimentares', models.CharField(default='', max_length=250)),
                ('coposAguaDia', models.IntegerField(default=0)),
                ('banhosDia', models.IntegerField(default=0)),
                ('horasSono', models.IntegerField(default=0)),
                ('etilismo', models.BooleanField()),
                ('tabagismo', models.BooleanField()),
                ('alergiaTopica', models.BooleanField()),
                ('atividadeDomesticaPorDia', models.CharField(default='', max_length=250)),
            ],
            options={
                'verbose_name': 'Hábito Pessoal',
                'verbose_name_plural': 'Hábitos Pessoais',
            },
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacaoUicera', models.CharField(max_length=250)),
                ('condicoesPele', models.CharField(default='', max_length=250)),
                ('condicaoBordas', models.CharField(default='', max_length=250)),
                ('condicaoLeito', models.CharField(default='', max_length=250)),
                ('percentualLeito', models.FloatField(default=0)),
                ('tipoExsudato', models.CharField(default='', max_length=250)),
                ('quantidade', models.IntegerField(default=0)),
                ('odor', models.CharField(default='', max_length=250)),
                ('perdaTecidual', models.CharField(default='', max_length=250)),
                ('maiorExtensaoVertical', models.CharField(default='', max_length=250)),
                ('maiorExtensaoHorizontal', models.CharField(default='', max_length=250)),
                ('profundidade', models.BooleanField()),
                ('maiorProfundidade', models.FloatField(default=0)),
                ('sensibilidade', models.BooleanField()),
                ('zonaPeDireito', models.CharField(default='', max_length=250)),
                ('zonaPeEsquerdo', models.CharField(default='', max_length=250)),
                ('temperatura', models.FloatField(default=0)),
                ('parestesia', models.CharField(default='', max_length=250)),
                ('hipoestesia', models.CharField(default='', max_length=250)),
                ('pulsoPedioso', models.CharField(default='', max_length=250)),
                ('pulsoPopliteo', models.CharField(default='', max_length=250)),
                ('pulsoFemoral', models.CharField(default='', max_length=250)),
                ('tibiaPosterior', models.CharField(default='', max_length=250)),
                ('sinaisDeInfeccao', models.CharField(default='', max_length=250)),
            ],
            options={
                'verbose_name': 'Oberservação',
                'verbose_name_plural': 'Observações',
            },
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG31102018030233', max_length=80),
        ),
        migrations.AddField(
            model_name='paciente',
            name='habitoPessoal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='samuv_site.HabitosPessoais'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observacao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Observacao'),
        ),
    ]
