# Generated by Django 2.0.7 on 2018-10-31 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0019_auto_20181031_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG31102018030559', max_length=80),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='anamnese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Anamnese'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='habitoPessoal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_site.HabitosPessoais'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='observacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Observacao'),
        ),
    ]
