# Generated by Django 2.0.7 on 2018-10-31 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0020_auto_20181031_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosticoUsuario', models.CharField(default='', max_length=250)),
                ('diagnosticoEquipe', models.CharField(max_length=250)),
                ('diagnosticoPesquisadora', models.CharField(max_length=250)),
                ('resultadoExames', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Resultado Clinico',
                'verbose_name_plural': 'Resultados Clinicos',
            },
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG31102018031423', max_length=80),
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinico',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Clinico'),
        ),
    ]
