# Generated by Django 2.0.7 on 2018-10-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0021_auto_20181031_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnica',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG31102018031800', max_length=80),
        ),
    ]
