# Generated by Django 2.0.7 on 2018-11-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0023_auto_20181107_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='paciente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Paciente'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG16112018093054', max_length=80),
        ),
    ]
