# Generated by Django 2.0.7 on 2018-11-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0025_auto_20181116_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='fechamentoUlcera',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='ulceraAtual',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG16112018095115', max_length=80),
        ),
    ]
