# Generated by Django 2.0.7 on 2018-11-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0026_auto_20181116_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='culturaSecrecao',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='internacao',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG16112018095924', max_length=80),
        ),
    ]
