# Generated by Django 2.0.7 on 2018-11-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0027_auto_20181116_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='interrupcaoTratamento',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG16112018104806', max_length=80),
        ),
    ]
