# Generated by Django 2.0.7 on 2018-11-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0030_auto_20181116_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinico',
            name='paciente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Paciente'),
        ),
        migrations.AddField(
            model_name='habitospessoais',
            name='paciente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Paciente'),
        ),
        migrations.AddField(
            model_name='observacao',
            name='paciente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Paciente'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG16112018024840', max_length=80),
        ),
    ]
