# Generated by Django 2.0.7 on 2018-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0031_auto_20181116_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observacao',
            old_name='condicoesPele',
            new_name='condicaoPele',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG16112018025200', max_length=80),
        ),
    ]
