# Generated by Django 2.0.7 on 2018-11-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0032_auto_20181116_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG16112018045613', max_length=80),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='profundidade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='sensibilidade',
            field=models.CharField(default='', max_length=250),
        ),
    ]
