# Generated by Django 2.0.7 on 2018-11-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0033_auto_20181116_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG16112018045626', max_length=80),
        ),
    ]
