# Generated by Django 2.0.7 on 2018-11-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0036_auto_20181116_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observacao',
            old_name='localizacaoUicera',
            new_name='localizacaoUlcera',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG16112018051255', max_length=80),
        ),
    ]
