# Generated by Django 2.0.7 on 2018-11-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0037_auto_20181116_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='imagemAnalisada',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG16112018094356', max_length=80),
        ),
    ]
