# Generated by Django 2.0.7 on 2018-11-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0038_auto_20181116_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='profissional',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG16112018104832', max_length=80),
        ),
    ]
