# Generated by Django 2.0.7 on 2018-11-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0043_auto_20181122_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='clinica',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG22112018034355', max_length=80),
        ),
    ]
