# Generated by Django 2.0.7 on 2018-11-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0044_auto_20181122_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG22112018034636', max_length=80),
        ),
    ]
