# Generated by Django 2.0.7 on 2018-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0047_auto_20181122_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='endereco',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='nome',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG22112018040252', max_length=80),
        ),
    ]
