# Generated by Django 2.0.7 on 2018-12-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0051_auto_20181122_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnese',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='clinico',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='habitospessoais',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='observacao',
            name='paciente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='anamnese',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Anamnese'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinico',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Clinico'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='habitos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='samuv_site.HabitosPessoais'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observacao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='samuv_site.Observacao'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG04122018105249', max_length=80),
        ),
    ]
