# Generated by Django 2.0.7 on 2018-12-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0052_auto_20181204_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='usuario',
        ),
        migrations.AddField(
            model_name='profissional',
            name='email',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='idProfissional',
            field=models.AutoField(default='', primary_key=True, serialize=False, verbose_name='auth.User'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='login',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='nomeProfissional',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='senha',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG04122018023031', max_length=80),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
