# Generated by Django 2.0.7 on 2018-12-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0053_auto_20181204_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG04122018023536', max_length=80),
        ),
    ]
