# Generated by Django 2.0.7 on 2018-12-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0055_auto_20181204_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG06122018110605', max_length=80),
        ),
    ]
