# Generated by Django 2.0.7 on 2018-12-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_site', '0056_auto_20181206_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG06122018025411', max_length=80),
        ),
    ]
